### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by cdeck95**

### CODE REVIEW

**Comment by cdeck95** [comment]
@Coontm12, please review this PR & have all tests done by Wed @ 12pm EST. 

 Test Cases: https://docs.google.com/spreadsheets/d/1SZO7zRY_TfFzcovbwJhP9vuIRAO80CurnXgUd_-hVbg/edit?usp=sharing 

 Dev Site: https://tags-dev.discrescuenetwork.com

**Comment by Coontm12** [comment]
@cdeck95 Testing is done. 2 bugs found 
https://docs.google.com/spreadsheets/d/1SZO7zRY_TfFzcovbwJhP9vuIRAO80CurnXgUd_-hVbg/edit?usp=sharing

**Comment by cdeck95** [comment]
@Coontm12 retest needed for PR83-TASK8 & PR83-TASK4
image

**Review by Coontm12 — APPROVED** [review]
Changes fixed after successful deployment

**Pull request merged**
